# Generated by Django 5.2.8 on 2025-12-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
