# Generated by Django 5.2.8 on 2025-12-02 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_photo'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher'),
        ),
    ]
