# Generated by Django 5.2.8 on 2025-12-02 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_teacher_id'),
        ('teachers', '0003_remove_teacher_class_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='teacher_id_display',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
    ]
