# Generated by Django 5.2.8 on 2025-12-02 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_student_teacher_id_student_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher_id_display',
        ),
    ]
