# Generated by Django 5.2.8 on 2025-12-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_remove_student_teacher_id_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
