# Generated by Django 5.2.8 on 2025-12-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_student_course'),
        ('teachers', '0010_alter_notification_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='teachers.courses'),
        ),
    ]
