# Generated by Django 5.2.8 on 2025-12-02 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('teachers', '0002_remove_teacher_subject_teacher_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher'),
        ),
    ]
