# Generated by Django 5.2.8 on 2025-12-02 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_remove_teacher_subject_teacher_class_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='class_id',
        ),
    ]
