# Generated by Django 5.2.8 on 2025-12-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
