# Generated by Django 5.2.8 on 2025-12-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_fees_alter_courses_duration_studentcoursepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentcoursepayment',
            name='paid_date',
            field=models.DateField(null=True),
        ),
    ]
